CREATE DATABASE IF NOT EXISTS finbot
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'finbot'@'%' IDENTIFIED BY 'finbot_password';

GRANT ALL PRIVILEGES ON finbot.* TO 'finbot'@'%';

FLUSH PRIVILEGES;